### ISSUE TITLE
Dark Theme breaks fragment colors for dates and times

### ISSUE THREAD

**Issue by BenHarperStudent** [AKmeier/Sieve-Mobile-Application#26]

**Comment by HFocus** [comment]
![image](https://user-images.githubusercontent.com/31972815/52149743-ff95cc80-262a-11e9-8002-87d188ae98af.png)

**Comment by HFocus** [comment]
I looked at it further. It seems to be an issue where the text in the calendar is changed to white but the rest of the calendar stays the same. A possible fix might be extending the theme switchings to the calendar and time dialogs. I will open a branch called dialog-themes to address this.

**Comment by AKmeier** [comment]
More info:
- The text color and accent colors change
- The top bar color does not change
- The background color does not change

**Comment by BenHarperStudent** [comment]
I think I have a fix now, although we might want to add extra theme options for the other themes, fix is on Date_and_TimePicker_Bugfixing branch

**Comment by BenHarperStudent** [comment]
Fixed :P, although in a really janky way
