### ISSUE TITLE
Double tapping Edit Task in Assignment Details sets Priority to Low

### ISSUE THREAD

**Issue by HFocus** [AKmeier/Sieve-Mobile-Application#30]
How to Replicate:
- Create a task with priority high
- Open it in assignment details
- Double tap the Edit Task button
- Go back to home page
- See that priority is now low

**Comment by BenHarperStudent** [comment]
Not just high priority, but also medium

**Comment by BenHarperStudent** [comment]
This also makes the app crash when the task is selected again

**Comment by BenHarperStudent** [comment]
Interestingly, error is caused by class selection spinner

**Comment by BenHarperStudent** [comment]
Found error, it was a problem with class for inserting to db. When class was not selected, it registered it as a null, error is now fixed
