### ISSUE TITLE
Basic Push Notifications

### ISSUE THREAD

**Issue by HFocus** [AKmeier/Sieve-Mobile-Application#5]
Add a feature to send a notification to users the day before a task is due.

**Comment by BenHarperStudent** [comment]
Basic functionality before Oreo and after Oreo, still needs to send at the correct times and include names of assignments due

**Comment by HFocus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [blank](https://trello.com/c/t8bR4d0M/1-blank)

**Comment by HFocus** [comment]
f689cf98fd3a4df727c0a3cdfc880cf2fbf333cf

**Comment by BenHarperStudent** [comment]
Basic Push Notifications are finished!
